# Generated by Django 4.0.5 on 2022-06-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socks',
            new_name='Sock',
        ),
    ]
